name = "fpt-portal-v2-rebuild-student-dev"
main = "src/index.js"
compatibility_date = "2026-08-20"
workers_dev = true

[vars]
ENVIRONMENT = "development"
DEPLOYMENT_IDENTITY = "student-development"
CHECKPOINT = "2"
BASELINE_SOURCE_SHA = "e4c7bde7ad9a9402136da5798d7ab690ab30322c"

[env.staging]
name = "fpt-portal-v2-rebuild-student-staging"
workers_dev = true

[env.staging.vars]
ENVIRONMENT = "staging"
DEPLOYMENT_IDENTITY = "student-staging"
CHECKPOINT = "2"
BASELINE_SOURCE_SHA = "e4c7bde7ad9a9402136da5798d7ab690ab30322c"
