name = "fpt-portal-v2-rebuild-browser-staging-cp9"
main = "src/index.js"
compatibility_date = "2026-08-20"
workers_dev = true

[vars]
UPSTREAM_ORIGIN = "https://fpt-portal-v2-rebuild-student-staging.futureperfectlessons.workers.dev"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
