import crypto from 'node:crypto';
import fs from 'node:fs';

const VERSION='1.0';
const AUTHORITY='v1.3';
const D1_ID='5b988d3d-341a-492d-8e40-8d4efa66150e';
const D1_NAME='fpt-11plus-practice';
const QUIZ_WORKER='futureperfect-11plus-practice-step10-preview';
const DIRECT=['quiz_auth_session','quiz_generation_lock','quiz_audit_event','quiz_recommendation','student_skill_profile','attempt','exposure_history','quiz_session'];
const CHILD=['quiz_session_runtime','quiz_answer_draft','quiz_question'];
const REQUIRED=[...DIRECT,...CHILD,'question_aggregate','question_instance','question_family'];

const E=(n,d='')=>process.env[n]??d;
const die=m=>{throw new Error(m)};
const h=s=>crypto.createHash('sha256').update(s).digest('hex');
function canon(v){if(Array.isArray(v))return`[${v.map(canon).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function date(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))die('retention_date must be YYYY-MM-DD');const d=new Date(v+'T00:00:00Z');if(d.toISOString().slice(0,10)!==v)die('invalid retention_date')}
function label(v){if(!/^[A-Za-z0-9._ -]{1,80}$/.test(v))die('invalid cohort_label');return v}
function parts(a,n=75){const o=[];for(let i=0;i<a.length;i+=n)o.push(a.slice(i,i+n));return o}
const qs=n=>Array.from({length:n},()=>'?').join(',');
const rows=r=>r.flatMap(x=>Array.isArray(x.results)?x.results:[]);
function ro(r,what){for(const x of r){if(x?.meta?.changed_db===true||Number(x?.meta?.changes||0)!==0||Number(x?.meta?.rows_written||0)!==0)die(`${what}: read-only invariant failed`)}}

function manifest(raw,cfg){let x;try{x=JSON.parse(raw)}catch{die('RETENTION_TARGET_MANIFEST_JSON is invalid JSON')};if(!x||Array.isArray(x))die('manifest must be object');const ids=(x.portalUserIds||[]).map(v=>String(v).trim());if(x.authorityVersion!==AUTHORITY||x.authorityVersion!==cfg.authority)die('manifest authority mismatch');if(String(x.cohortLabel)!==cfg.cohort)die('manifest cohort mismatch');if(String(x.retentionDate)!==cfg.retentionDate)die('manifest retention date mismatch');date(String(x.retentionDate));if(ids.length<1||ids.length>500)die('manifest target count must be 1..500');if(ids.some(v=>!v||v.length>256||/[\r\n\0]/.test(v)))die('invalid portal user id');const unique=[...new Set(ids)].sort();if(unique.length!==ids.length)die('duplicate portal user id');const safe={authorityVersion:AUTHORITY,cohortLabel:cfg.cohort,retentionDate:cfg.retentionDate,portalUserIds:unique};return{...safe,sha256:h(canon(safe))}}

async function cf(path,{method='GET',body}={}){const account=E('CLOUDFLARE_ACCOUNT_ID'),token=E('CLOUDFLARE_API_TOKEN');if(!account||!token)die('Cloudflare credentials unavailable');const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${account}${path}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let j;try{j=JSON.parse(t)}catch{die(`Cloudflare non-JSON HTTP ${r.status}`)};if(!r.ok||j.success!==true)die(`Cloudflare API error HTTP ${r.status}: ${JSON.stringify(j.errors||j)}`);return j}
async function query(sql,params=[]){const j=await cf(`/d1/database/${D1_ID}/query`,{method:'POST',body:{sql,params}});if(!Array.isArray(j.result)||j.result.some(x=>x.success!==true))die('D1 query failed');return j.result}
async function batch(items){const j=await cf(`/d1/database/${D1_ID}/query`,{method:'POST',body:{batch:items}});if(!Array.isArray(j.result)||j.result.some(x=>x.success!==true))die('D1 batch failed');return j.result}

async function identity(){const d=await cf(`/d1/database/${D1_ID}`);if(d.result?.uuid!==D1_ID||d.result?.name!==D1_NAME)die('D1 identity mismatch');const s=await cf(`/workers/scripts/${QUIZ_WORKER}/settings`);const b=(s.result?.bindings||[]).find(x=>x.name==='DB');if((b?.id||b?.database_id)!==D1_ID)die('Quiz Worker DB binding mismatch');return{database:{name:D1_NAME,uuid:D1_ID},worker:QUIZ_WORKER,binding:'DB'}}
async function bookmark(){const j=await cf(`/d1/database/${D1_ID}/time_travel/bookmark`);const b=j.result?.bookmark;if(!b)die('Time Travel bookmark unavailable');return b}
async function schema(){const r=await query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name");ro(r,'schema');const n=new Set(rows(r).map(x=>x.name));const m=REQUIRED.filter(x=>!n.has(x));if(m.length)die('required tables missing: '+m.join(','))}
async function directCounts(ids){const out=Object.fromEntries(DIRECT.map(x=>[x,0]));for(const p of parts(ids)){const r=await batch(DIRECT.map(t=>({sql:`SELECT COUNT(*) AS n FROM ${t} WHERE portal_user_id IN (${qs(p.length)})`,params:p})));ro(r,'direct counts');DIRECT.forEach((t,i)=>out[t]+=Number(rows([r[i]])[0]?.n||0))}return out}
async function sessions(ids){const out=[];for(const p of parts(ids)){const r=await query(`SELECT session_id FROM quiz_session WHERE portal_user_id IN (${qs(p.length)}) ORDER BY session_id`,p);ro(r,'session ids');out.push(...rows(r).map(x=>x.session_id))}return out}
async function childCounts(ids){const out=Object.fromEntries(CHILD.map(x=>[x,0]));for(const p of parts(ids)){const r=await batch(CHILD.map(t=>({sql:`SELECT COUNT(*) AS n FROM ${t} WHERE session_id IN (${qs(p.length)})`,params:p})));ro(r,'child counts');CHILD.forEach((t,i)=>out[t]+=Number(rows([r[i]])[0]?.n||0))}return out}
async function active(ids){let n=0;for(const p of parts(ids)){const r=await query(`SELECT COUNT(*) AS n FROM quiz_session qs LEFT JOIN quiz_session_runtime rt ON rt.session_id=qs.session_id WHERE qs.portal_user_id IN (${qs(p.length)}) AND qs.status='IN_PROGRESS' AND COALESCE(rt.submission_reason,'')<>'ABANDONED'`,p);ro(r,'active sessions');n+=Number(rows(r)[0]?.n||0)}return n}
async function aggregate(){const i=await query("PRAGMA table_info('question_aggregate')");ro(i,'aggregate schema');const cols=rows(i).map(x=>x.name);if(!cols.length)die('question_aggregate schema missing');const order=cols.slice(0,Math.min(2,cols.length)).map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',');const r=await query(`SELECT * FROM question_aggregate ORDER BY ${order}`);ro(r,'aggregate');return{rowCount:rows(r).length,sha256:h(canon(rows(r)))}}
async function globals(){const r=await batch([{sql:"SELECT COUNT(*) AS n FROM question_instance WHERE UPPER(lifecycle_status)='LIVE'",params:[]},{sql:"SELECT COUNT(DISTINCT family_id) AS n FROM question_instance WHERE UPPER(lifecycle_status)='LIVE'",params:[]},{sql:'PRAGMA foreign_key_check',params:[]}]);ro(r,'global');return{liveQuestions:Number(rows([r[0]])[0]?.n||0),liveFamilies:Number(rows([r[1]])[0]?.n||0),foreignKeyViolations:rows([r[2]]).length}}
async function dryArtifact(run){const token=E('GITHUB_TOKEN'),repo=E('GITHUB_REPOSITORY');if(!token||!repo)die('GitHub verification context missing');const r=await fetch(`https://api.github.com/repos/${repo}/actions/runs/${run}/artifacts?per_page=100`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)die('cannot verify dry-run artifact');const j=await r.json();if(!(j.artifacts||[]).some(a=>!a.expired&&String(a.name||'').startsWith('cp1-retention-v1-dry-run-')))die('referenced dry-run artifact absent/expired')}

function applyGuards(c,m,b){if(c.mode!=='apply')return;if(c.retentionDate.slice(5)!=='09-10')die('apply only permitted for 10 September');if(c.retentionDate!==new Date().toISOString().slice(0,10))die('apply only permitted on exact UTC retention date');if(c.manifestSha!==m.sha256)die('manifest SHA mismatch');if(!c.rollback||c.rollback!==b)die('rollback bookmark changed; rerun dry-run');if(!/^\d+$/.test(c.dryRun))die('dry-run run id required');if(c.approval.length<8)die('separate owner approval reference required');if(c.maintenance!=='true')die('maintenance window confirmation required');const phrase=`PURGE QUIZ STUDENT DATA ${c.cohort} ON ${c.retentionDate}`;if(c.confirm!==phrase)die('typed destructive confirmation mismatch')}
function deletes(ids){const o=[];for(const p of parts(ids)){for(const t of DIRECT)o.push({sql:`DELETE FROM ${t} WHERE portal_user_id IN (${qs(p.length)})`,params:p})}return o}

async function main(){const c={mode:E('RETENTION_MODE','dry-run').toLowerCase(),authority:E('AUTHORITY_VERSION',AUTHORITY),cohort:label(E('COHORT_LABEL')),retentionDate:E('RETENTION_DATE'),manifestSha:E('EXPECTED_MANIFEST_SHA256'),rollback:E('EXPECTED_ROLLBACK_BOOKMARK'),dryRun:E('DRY_RUN_RUN_ID'),approval:E('APPLY_APPROVAL_REF'),maintenance:E('MAINTENANCE_WINDOW_CONFIRMED','false'),confirm:E('DESTRUCTIVE_CONFIRMATION'),fixture:E('CONTROL_VERIFICATION_FIXTURE')==='1'};if(!['dry-run','apply'].includes(c.mode))die('mode must be dry-run or apply');if(c.authority!==AUTHORITY)die(`control v1.0 pinned to ${AUTHORITY}`);date(c.retentionDate);if(E('EXPECTED_D1_UUID',D1_ID)!==D1_ID)die('D1 UUID pin mismatch');const m=manifest(E('RETENTION_TARGET_MANIFEST_JSON'),c);if(c.manifestSha&&c.manifestSha!==m.sha256)die('manifest SHA mismatch');const id=await identity();await schema();const b=await bookmark();applyGuards(c,m,b);if(c.mode==='apply')await dryArtifact(c.dryRun);
const beforeD=await directCounts(m.portalUserIds),sid=await sessions(m.portalUserIds),beforeC=sid.length?await childCounts(sid):Object.fromEntries(CHILD.map(x=>[x,0])),act=await active(m.portalUserIds),agg=await aggregate(),g=await globals();if(act)die(`target has ${act} active non-abandoned session(s)`);if(g.liveQuestions!==714||g.liveFamilies!==91||g.foreignKeyViolations!==0)die('global baseline mismatch');const matched=Object.values(beforeD).reduce((a,b)=>a+b,0);if(!c.fixture&&matched===0)die('manifest matched zero student-linked rows');let writes=0,post=null,apply=null;if(c.mode==='apply'){const d=deletes(m.portalUserIds);writes=d.length;const r=await batch(d);apply={statements:r.length,totalChanges:r.reduce((n,x)=>n+Number(x?.meta?.changes||0),0)};const ad=await directCounts(m.portalUserIds),ac=sid.length?await childCounts(sid):Object.fromEntries(CHILD.map(x=>[x,0])),aa=await aggregate(),ag=await globals();if(Object.values(ad).some(Boolean)||Object.values(ac).some(Boolean))die('post-apply target rows remain');if(aa.sha256!==agg.sha256||aa.rowCount!==agg.rowCount)die('anonymous aggregate changed');if(ag.liveQuestions!==714||ag.liveFamilies!==91||ag.foreignKeyViolations!==0)die('post-apply global baseline mismatch');post={direct:ad,children:ac,aggregate:aa,global:ag}}
const audit={control:'cp1-retention-control',version:VERSION,authority:AUTHORITY,mode:c.mode,productionMutation:c.mode==='apply',writeOperationsAttempted:writes,cohort:c.cohort,retentionDate:c.retentionDate,manifest:{sha256:m.sha256,targetCount:m.portalUserIds.length,rawIdsPersisted:false},identity:id,rollbackBookmark:b,pre:{direct:beforeD,children:beforeC,activeNonAbandonedSessions:act,aggregate:agg,global:g},apply,post,github:{repository:E('GITHUB_REPOSITORY'),runId:E('GITHUB_RUN_ID'),sha:E('GITHUB_SHA')},generatedAt:new Date().toISOString()};const dir=E('RETENTION_AUDIT_DIR','retention-audit');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(`${dir}/cp1-retention-${c.mode}-audit.json`,JSON.stringify(audit,null,2));console.log(`CP1_RETENTION_${c.mode.toUpperCase()}_PASS`);console.log(`MANIFEST_SHA256=${m.sha256}`);console.log(`WRITE_OPERATIONS_ATTEMPTED=${writes}`)}

main().catch(e=>{console.error('CP1_RETENTION_CONTROL_FAIL: '+e.message);process.exit(1)});
